"""
Django settings for vkusotiiki project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from .base_settings import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dn0#iyk_ct_@_c0o=u%%ow0^i=1-!&+d^6r_31sp4tf&r*f2%0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':  'django.db.backends.postgresql_psycopg2',
        'NAME':    'vkusotiiki',
        'USER':     'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        # 'PORT': 3352  # mysql
        # 'PORT': 5432  # postgres
    }
}
