# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20161217_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='filer.Image'),
        ),
    ]
