# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20161217_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
    ]
