# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20161217_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
