# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0007_auto_20161217_1529'),
        ('recipes', '0011_auto_20161230_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(default='', max_length=75, verbose_name='Firebase ID')),
                ('is_business', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Phone number for business users.')),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address for business users.')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='filer.Image')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
