# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.UserProfile'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.UserProfile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=b'', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.UserProfile'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth_id',
            field=models.CharField(default=b'', max_length=75, unique=True, verbose_name=b'Firebase ID'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'recipe', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('ingredient', 'recipe', 'quantity')]),
        ),
    ]
