# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170107_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Recipe'),
        ),
    ]
